# Generated by Django 3.2.12 on 2024-03-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('category', models.CharField(max_length=20)),
                ('product_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
